spring.application.name=SkillSphere
spring.datasource.url=jdbc:mysql://hopper.proxy.rlwy.net:58916/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=HZaRPhbmQDEgGkwVkxLKRKHiaqKrcGla
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=94a08da1fecbb6e8b46990538c7b50b2401f8f309a47b853509923831804f51d
jwt.expiration=86400000

server.port=8080
